#Server Configuration
server:
  port: 8080

domain:
  name: localhost

#Spring configuration
spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

#Logging Configuration.
logging:
  file: ${java.io.tmpdir}/shortener-application.log
  level.org.springframework.web: ERROR
